name: CI

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    env:
      platform: aws
      region: us-east-1
      account: 123456789012

      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}


    runs-on: ubuntu-latest

    steps:
    - name: "Mostrar Mensaje"
      run: echo "Hola Mundo"

    - name: "Mostrar Variables de Entorno"
      run: |
        echo "Plataforma: ${{ env.platform }}"
        echo "Region: ${{ env.region }}"
        echo "Cuenta: ${{ env.account }}"

        echo "Este es el valor de username: ${{ env.username }}"
        echo "Este es el valor de password: ${{ env.password }}"

        echo "Project version is ${{ vars.PROJECT_VERSION }}"

    - name: "Mostrando valores solo si el usuario es correcto"
      if: ${{ env.username != '' && env.password != '' }}
      run:
        echo "El usuario es correcto"
    
    - name: "Mostrar Variables por defecto"
      run: |
        echo "Evento: ${{ toJson(github.event) }}"
        echo "Github_ACTOR: ${{ github.actor }}"
        echo "Github_REPOSITORY: ${{ github.repository }}"